using System.Text.RegularExpressions;

namespace Telepresence.NET.InterceptSpec;

/// <summary>
/// Configures the Preview URL generated by Telepresence Enterprise.
/// </summary>
internal class PreviewUrl
{
    private readonly IDictionary<string, string>? _extraHeaders;

    /// <summary>
    /// Enable preview URL.
    /// Default is true.
    /// </summary>
    public bool? Enable { get; init; } = true;

    /// <summary>
    /// Display banner on preview page.
    /// Default is true.
    /// </summary>
    public bool? Banner { get; init; } = true;

    public Ingress? Ingress { get; init; }

    /// <summary>
    /// Additional headers in key1=value1,key2=value2 pairs injected in every preview page request.
    /// </summary>
    public IDictionary<string, string>? ExtraHeaders
    {
        get => _extraHeaders;
        init
        {
            if (value == null || !value.Any())
                return;

            const string pattern = "^[a-zA-Z][a-zA-Z0-9._-]*$";

            if (value.Any(header => !Regex.IsMatch(header.Key, pattern)))
                throw new InvalidOperationException(Constants.Exceptions.AlphaNumericWithHyphensUnderscoresDots);

            _extraHeaders = value;
        }
    }
}